<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>Facepunch.Steamworks.Posix</AssemblyName>
		<DefineConstants>$(DefineConstants);PLATFORM_POSIX</DefineConstants>
		<TargetFrameworks>netstandard2.1;net10.0;net46</TargetFrameworks>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<LangVersion>10</LangVersion>	
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<RootNamespace>Steamworks</RootNamespace>
	</PropertyGroup>

	<Import Project="Facepunch.Steamworks.targets" />

	<ItemGroup>
		<Content Include="lib/linux32/libsteam_api.so">
			<PackagePath>runtimes/linux-x86/native</PackagePath>
			<Pack>true</Pack>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>runtimes/linux-x86/native/libsteam_api.so</Link>
		</Content>

		<Content Include="lib/linux64/libsteam_api.so">
			<PackagePath>runtimes/linux-x64/native</PackagePath>
			<Pack>true</Pack>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>runtimes/linux-x64/native/libsteam_api.so</Link>
		</Content>

		<Content Include="lib/linuxarm64/libsteam_api.so">
			<PackagePath>runtimes/linux-arm64/native</PackagePath>
			<Pack>true</Pack>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<Link>runtimes/linux-arm64/native/libsteam_api.so</Link>
		</Content>
	</ItemGroup>

</Project>
